"""empty message

Revision ID: 78886a6a4394
Revises: 32fdf0c65d40
Create Date: 2023-02-23 03:58:54.479370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78886a6a4394'
down_revision = '32fdf0c65d40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
